apiVersion: v1
kind: Pod
metadata: 
 name: config-map-new
 labels:
    app: config_info
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "/bin/sh", "-c", "env"]
    env:
    - name: STUDENT_NAME
      valueFrom:
        configMapKeyRef:
          name: my-app
          key: student_name
    - name: SCHOOL_NAME
      valueFrom:
        configMapKeyRef:
          name: my-app
          key: school
    - name: KUBERNETES_EXPERIENCE
      valueFrom:
        configMapKeyRef:
          name: my-app
          key: kuberenetes
  restartPolicy: Never
