apiVersion: v1
kind: ReplicationController
metadata: 
 name: testreplication
# labels: 
#  app: testrep
spec:
 replicas: 3
 selector:
#  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    app: nginx
  spec:
    containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80 
    
  
