apiVersion: v1
kind: Pod
metadata: 
 name: test-pod
spec:
 containers:
 - name: busybox
   image: busybox
   command: ["env"]
   env:
   - name: NAME
     value: "VINAY"
   - name: GAME
     value: "CRICKET"
 restartPolicy: Never
